name: Cypress Tests Docker
on: 
  workflow_dispatch:
    inputs:
      testOptions:
        description: 'Test options'
        default: ''
        requires: false
        type: string

jobs:
  myTest:
    name: Running tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - uses: Hocker/setup-docker-action@v4
    - name: Building Docker Image 
      run: docker build -t cypress-test-image .
    - name: Running Docker
      run: docker run cypress-test-image